### ISSUE TITLE
StopIteration & VDJ Sequencing

### ISSUE THREAD

**Issue by lindsly** [nanoporetech/medaka#231] opened 2020-12-05 00:14 UTC
**Describe the bug**
StopIteration occurs when accessing common.py - checking compatibility with Python 3.8. Also, a more general question about finding consensus sequences for variable heavy chain locus (VDJ).

**Logging**
Command:
`medaka_consensus -d chr12.fa -i fastq_pass_ova_6/all_guppy.fastq -o medaka_output

Success for a while:
```
Checking program versions
This is medaka 1.2.1
Program    Version    Required   Pass     
bcftools   1.10.2     1.9        True     
bgzip      1.10.2     1.9        True     
minimap2   2.17       2.11       True     
samtools   1.10       1.9        True     
tabix      1.10.2     1.9        True
```
.
.
.
```
[18:28:02 - Feature] Processed chr12:114879888.0-114880371.0 (median depth 52.0)
[18:28:02 - Sampler] Took 0.04s to make features.
[18:28:04 - PWorker] All done, 0 remainder regions.
[18:28:04 - Predict] Finished processing all regions.
```
Error (immediately after above line ^):
```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lindsly/miniconda2/envs/medaka/lib/python3.8/site-packages/medaka/common.py", line 425, in trim_samples
    s1 = next(sample_gen)
StopIteration
```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method : conda 
 - OS: Ubuntu 18.04
 - No GPU? (running in Oracle VM VirtualBox)

**Additional context**
I saw a [similar bug](https://github.com/nanoporetech/medaka/issues/74#issue-485549225) from last year where the issue was that Medaka only supports Python 3.5/3.6 - is this still the case?

**Additional question**
I am trying to create a consensus of the variable heavy chain locus on chromosome 12 (all of my reads are at this specific location). I am currently using the chr 12 reference genome as my -d parameter. This region has many different sequences (due to VDJ recombination), so I don't know if creating a consensus sequence for all my sequences is the correct approach. 

Is there another way that I should approach this problem - maybe to generate multiple consensus sequences with subsets of my data? If so, how would I go about doing this?

**Comment by mwykes** [comment] 2020-12-21 12:00
Hi @lindsly, medaka [now has wheels](123) for python 3.7 and 3.8, but these are largely untested. Can you try with python 3.5/3.6 and see if the issue goes away? 

In response to your question about VDJ recombination, as you say, if you are able to somehow partition your reads into subsets which should share the same consensus sequence, you could run medaka on each subset. This is how diploid variant calling is performed in medaka; whatshap is used to partition reads into two haplotypes using heterozygous SNPs, and a medaka consensus is calculated separately for each haplotype from the reads assigned to that haplotype. However, unfortunately I cannot recommend a particular approach for separating your VDJ data into subsets.

**Comment by lbal-biomat** [comment] 2021-01-03 12:16
Hi,
In case someone needs this, the StopIteration error occurs because since python3.7 StopIteration exceptions are transformed into RuntimeError exceptions. In previous versions that they were silenty swallowed. It's just a line of code so it's very easy to change. Around the line indicated by the traceback there will be this piece of code:
```
except StopIteration:
    if len(batch) > 0:
        yield batch
    raise StopIteration
```
To work as intended with >3.7 you need to change the last line so that piece of code looks like this:
```
except StopIteration:
    if len(batch) > 0:
        yield batch
    return
```

**Comment by cjw85** [comment] 2021-01-26 15:42
@lbal-biomat Which version of the source did you have? The changes you have indicated have been in public released for a while now (they're certainly in the master branch on GitHub as of this moment).

**Comment by lbal-biomat** [comment] 2021-01-29 18:27
@cjw85 Yes, I forgot to mention that I'm working with an old version (0.5.0) because I'm reproducing old results. I'm also working with the last version and definitely this problem didn't arise. It was just a little help in case someone else is trying something similar.

**Comment by cjw85** [comment] 2021-03-23 14:47
This issue has been resolved in later versions.

**Closed by cjw85** 2021-03-23 14:47 UTC
