### ISSUE TITLE
ModelStore exception <class 'NotImplementedError'>

### ISSUE THREAD

**Issue by xgnusr** [nanoporetech/medaka#282] opened 2021-03-30 09:37 UTC
Hi !!
Ubuntu 18.04
python 3.8
->
[11:29:23 - Predict] Using model: /mnt/conda/envs/medaka/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
[11:29:23 - DataStore] Writing sample registry.
[11:29:23 - Predict] Processing 142019 long region(s) with batching.
[11:29:23 - ModelStore] filepath /mnt/conda/envs/medaka/lib/python3.8/site-packages/medaka/data/r941_min_high_g360_model.hdf5

2021-03-30 11:29:23.918157: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[11:29:23 - ModelStore] ModelStore exception <class 'NotImplementedError'>

NotImplementedError: Cannot convert a symbolic Tensor (bidirectional/forward_gru1/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Could someone guide me on this error?

TNX !!

**Comment by cjw85** [comment] 2021-03-30 10:38
Hi @xgnusr,

What version of medaka are you using? This error occured with previous medaka versions but we believe it should be resolved in the latest version.

**Comment by xgnusr** [comment] 2021-03-30 12:14
Hi !!

I think it is a problem of incompatibilities between the different versions of the tools that are incorporated when invoking:

'conda create -n medaka -c conda-forge -c bioconda medaka'

**Comment by cjw85** [comment] 2021-03-30 14:47
Please can you confirm the version of medaka you are using. This can be done with either:

    medaka --version

or with 

    $ conda list | grep medaka

since you are using conda. The current version is v1.2.5. I have confirmed this to be working as expected after installing with:

    mamba create -n medaka -c conda-forge -c bioconda medaka

**Comment by xgnusr** [comment] 2021-03-30 15:39
Hi !
From 'conda create -n medaka -c conda-forge -c bioconda medaka' :
medaka --version:
medaka 1.2.5


TNX !!

**Comment by cjw85** [comment] 2021-03-30 15:56
Can you attempt to recreate your conda environment from scratch and then attach a file to this thread containing the output of the command:

    conda list

This is what I have:
[medaka_env.txt](https://github.com/nanoporetech/medaka/files/6230338/medaka_env.txt)

**Comment by xgnusr** [comment] 2021-03-31 10:28
Hi !
Now work perfectly !!
TNX 

(mamba create -n medaka -c conda-forge -c bioconda medaka)

**Closed** 2021-03-31 10:32 UTC
Labels: bug
