### ISSUE TITLE
Failed to call variants from consensus chunks

### ISSUE THREAD

**Issue by HJTsai** [nanoporetech/medaka#75] opened 2019-09-01 12:31 UTC
Hi, 

This is our command: 
medaka_variant -f /home/gits/ref/hg19.fa -i minimap2_reads.sorted_all.bam -t 12 -m r941_min_high -o medaka_SNP

After 1979m18.312s, it displays "Failed to call variants from consensus chunks."
![image](https://user-images.githubusercontent.com/49969700/64076422-641b2600-ccf7-11e9-9b93-b0a9e201374a.png)

What's wrong with our command?

HJ Tsai

**Comment by cjw85** [comment] 2019-09-04 13:20
This looks like a failed on our part. Your reference sequence has a lowercase "t" and the code is failing to handle this. We will take a look at why this is the case, as it seems like a regression.

I the meantime you might try using a reference sequence where all bases have been converted to uppercase (IUPAC ambiguity codes should be fine).

**Comment by cjw85** [comment] 2019-09-27 09:39
@HJTsai This issue should be resolved in medaka v0.9.2 available now on github and pypi.

**Closed** 2019-10-28 14:13 UTC
