### ISSUE TITLE
medaka_variant failed to call snps from consensus probabilities

### ISSUE THREAD

**Issue by MaestSi** [nanoporetech/medaka#160] opened 2020-05-20 05:45 UTC
Hi,
I am running `medaka_variant` v1.0.1 on a bam file obtained mapping amplicon reads to a reference composed of a single sequence called ref.
This is the command I used:
`medaka_variant -i BC06.bam -f reference.fasta -s r941_min_high_g360 -m r941_min_high_g360 -p medaka_phased.vcf -t 24`
This is the output I get:

> ++ Preparing data
> - Checking program versions
> Program    Version    Required   Pass
> bcftools   1.9        1.9        True
> bgzip      1.9        1.9        True
> minimap2   2.17       2.11       True
> samtools   1.9        1.9        True
> tabix      1.9        1.9        True
> 
> ++ Running first pass to haplotag reads.
> + Running consensus calling
> - Running medaka consensus with /path/to/BC06.bam --model /home/simone/miniconda3/envs/medaka_env/lib/python3.6/site-packages/medaka/data/r941_min_high_g360_model.hdf5
> [04:38:43 - Predict] Processing region(s): ref:0-17058
> [04:38:43 - Predict] Setting tensorflow threads to 1.
> [04:38:43 - Predict] Processing 1 long region(s) with batching.
> [04:38:43 - Predict] Using model: /home/simone/miniconda3/envs/medaka_env/lib/python3.6/site-packages/medaka/data/r941_min_high_g360_model.hdf5.
> [04:38:43 - ModelLoad] Building model with cudnn optimization: False
> OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
> OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
> OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-31
> OMP: Info #156: KMP_AFFINITY: 32 available OS procs
> OMP: Info #157: KMP_AFFINITY: Uniform topology
> OMP: Info #179: KMP_AFFINITY: 2 packages x 8 cores/pkg x 2 threads/core (16 total cores)
> OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
> OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 16 maps to package 0 core 0 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 1 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 18 maps to package 0 core 1 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 4 maps to package 0 core 2 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 20 maps to package 0 core 2 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 6 maps to package 0 core 3 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 22 maps to package 0 core 3 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 8 maps to package 0 core 8 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 24 maps to package 0 core 8 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 10 maps to package 0 core 9 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 26 maps to package 0 core 9 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 12 maps to package 0 core 10 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 28 maps to package 0 core 10 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 14 maps to package 0 core 11 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 30 maps to package 0 core 11 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 1 core 0 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 17 maps to package 1 core 0 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 1 core 1 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 19 maps to package 1 core 1 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 5 maps to package 1 core 2 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 21 maps to package 1 core 2 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 7 maps to package 1 core 3 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 23 maps to package 1 core 3 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 9 maps to package 1 core 8 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 25 maps to package 1 core 8 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 11 maps to package 1 core 9 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 27 maps to package 1 core 9 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 13 maps to package 1 core 10 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 29 maps to package 1 core 10 thread 1
> OMP: Info #171: KMP_AFFINITY: OS proc 15 maps to package 1 core 11 thread 0
> OMP: Info #171: KMP_AFFINITY: OS proc 31 maps to package 1 core 11 thread 1
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 34967 thread 0 bound to OS proc set 0
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 34967 thread 1 bound to OS proc set 2
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35170 thread 2 bound to OS proc set 4
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35172 thread 4 bound to OS proc set 8
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35177 thread 9 bound to OS proc set 3
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35171 thread 3 bound to OS proc set 6
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35173 thread 5 bound to OS proc set 10
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35186 thread 10 bound to OS proc set 5
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35175 thread 7 bound to OS proc set 14
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35176 thread 8 bound to OS proc set 1
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35174 thread 6 bound to OS proc set 12
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35192 thread 11 bound to OS proc set 7
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35197 thread 12 bound to OS proc set 9
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35205 thread 14 bound to OS proc set 13
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35203 thread 13 bound to OS proc set 11
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35206 thread 15 bound to OS proc set 15
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 35213 thread 16 bound to OS proc set 16
> [04:38:45 - DLoader] Initializing data loader
> [04:38:45 - PWorker] Running inference for 0.0M draft bases.
> [04:38:45 - Sampler] Initializing sampler for consensus of region ref:0-17058.
> [04:39:08 - Feature] Pileup counts do not span requested region, requested ref:0-17058, received 3184-15975.
> [04:39:08 - Feature] Processed ref:3184.0-15975.0 (median depth 8400.0)
> [04:39:08 - Feature] Pileup counts do not span requested region, requested ref:0-17058, received 16285-16566.
> [04:39:08 - Feature] Processed ref:16285.0-16566.0 (median depth 2.0)
> [04:39:08 - Feature] Pileup counts do not span requested region, requested ref:0-17058, received 16664-17049.
> [04:39:08 - Feature] Processed ref:16664.0-17049.0 (median depth 1.0)
> [04:39:08 - Sampler] Took 22.18s to make features.
> [04:39:08 - Sampler] Region ref:16285.0-16566.0 (296 positions) is smaller than inference chunk length 10000, quarantining.
> [04:39:08 - Sampler] Region ref:16664.0-17049.0 (395 positions) is smaller than inference chunk length 10000, quarantining.
> [04:39:08 - PWorker] Samples in cache: 0.
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38689 thread 17 bound to OS proc set 18
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38690 thread 18 bound to OS proc set 20
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38692 thread 20 bound to OS proc set 24
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38691 thread 19 bound to OS proc set 22
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38696 thread 21 bound to OS proc set 26
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38698 thread 23 bound to OS proc set 30
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38697 thread 22 bound to OS proc set 28
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38699 thread 24 bound to OS proc set 17
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38701 thread 26 bound to OS proc set 21
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38700 thread 25 bound to OS proc set 19
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38702 thread 27 bound to OS proc set 23
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38704 thread 28 bound to OS proc set 25
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38706 thread 30 bound to OS proc set 29
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38705 thread 29 bound to OS proc set 27
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38708 thread 31 bound to OS proc set 31
> OMP: Info #250: KMP_AFFINITY: pid 34402 tid 38709 thread 32 bound to OS proc set 0
> [04:39:40 - PWorker] 78.1% Done (0.0/0.0 Mbases) in 54.4s
> [04:39:40 - PWorker] All done, 2 remainder regions.
> [04:39:40 - Predict] Processing 2 short region(s).
> [04:39:40 - ModelLoad] Building model with cudnn optimization: False
> [04:39:42 - DLoader] Initializing data loader
> [04:39:42 - PWorker] Running inference for 0.0M draft bases.
> [04:39:42 - Sampler] Initializing sampler for consensus of region ref:16285-16567.
> [04:39:48 - Feature] Processed ref:16285.0-16566.0 (median depth 2.0)
> [04:39:48 - Sampler] Took 5.84s to make features.
> [04:39:48 - PWorker] Samples in cache: 0.
> [04:39:50 - PWorker] All done, 0 remainder regions.
> [04:39:50 - DLoader] Initializing data loader
> [04:39:50 - PWorker] Running inference for 0.0M draft bases.
> [04:39:50 - Sampler] Initializing sampler for consensus of region ref:16664-17050.
> [04:39:50 - Feature] Processed ref:16664.0-17049.0 (median depth 1.0)
> [04:39:50 - Sampler] Took 0.00s to make features.
> [04:39:51 - PWorker] All done, 0 remainder regions.
> [04:39:51 - Predict] Finished processing all regions.
> + Running snp calling
> - Running medaka snp
> [04:39:55 - DataIndex] Loaded 1/1 (100.00%) sample files.
> [04:39:55 - SNPs] Processing ref:0-.
> Traceback (most recent call last):
>   File "/home/simone/miniconda3/envs/medaka_env/bin/medaka", line 11, in <module>
>     sys.exit(main())
>   File "/home/simone/miniconda3/envs/medaka_env/lib/python3.6/site-packages/medaka/medaka.py", line 643, in main
>     args.func(args)
>   File "/home/simone/miniconda3/envs/medaka_env/lib/python3.6/site-packages/medaka/variant.py", line 197, in snps_from_hdf
>     reference=reg.ref_name).upper()
>   File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
> KeyError: "sequence 'ref' not present"
> * Failed to call snps from consensus probabilities.
> 

Is this issue somehow related to [this one](https://github.com/nanoporetech/medaka/issues/159)?
Thanks in advance,
Simone

**Comment by mwykes** [comment] 2020-05-20 08:35
Hi @MaestSi, 
It looks like the error in the traceback is due to pysam not finding the contig 'ref' in the reference fasta file. Can you check the names of the contigs match up in your reference and bam (by running e.g. samtools idxstats BC06.bam).

It is worth mentioning that though your choice of models is a valid workflow, it is not optimal for diploid variant calling with respect to a reference; we have specialised models (e.g. r941_prom_snp_g322) to call heterozygous SNPs used to phase reads and models trained for calling SNPs and indels on each haplotype (e.g. r941_prom_variant_g322). Variant calling models for g360 are not yet available, but will be released when they are. Furthermore, the tool medaka uses for phasing (whathap) does not generally work with amplicon data. If you just want SNPs (rather than SNPs and indels) on your amplicon data, you could use the -S option to medaka_variant, which stops after diploid SNP calling.

**Comment by MaestSi** [comment] 2020-05-20 12:00
Here is the output of `samtools idxstats BC06.bam`

> ref     17058   34198   0
> \*       0       0       4

ref is the only contig in the reference.fasta file. I already used successfully WhatsHap on those data, after calling variants with Illumina, so I guess there is something else that is not working. Do you have any suggestions?

**Comment by MaestSi** [comment] 2020-05-28 07:56
Are there any news on this? Moreover, I don't understand the reason why the 'bug' label was replaced by the 'enhancement' label. 
Thanks,
Simone

**Comment by mwykes** [comment] 2020-06-01 09:10
Hi @MaestSi, if you are able to share your bam and reference file, we can try to reproduce the issue and investigate what is going on.

**Comment by MaestSi** [comment] 2020-06-01 13:05
Thank you, I just shared the files privately via e-mail.
Simone

**Comment by mwykes** [comment] 2020-06-01 13:46
Thanks for sharing the files; I ran 

`medaka_variant -i BC06.bam -f reference.fasta -s r941_min_high_g360 -m r941_min_high_g360 -t 24` 

and it worked for me; I did not see the pysam KeyError you did. 

I removed the -p option to phase the final vcf as this will not work until #161 is resolved, but #161 is not responsible for the error you saw; it has a different traceback. 

I created a fresh installation of medaka via conda and pysam v0.15.4 was installed in my conda env. 

Can you try reinstalling medaka and running the command above?

**Comment by MaestSi** [comment] 2020-06-01 14:15
Hi, I created a fresh conda installation of medaka, but I keep getting the same error, also without `-p` parameter. The only case where I don't get the error is when a folder `medaka_variant/` already exists in the current directory. However, in the latter case, the produced vcf files are empty a part from the header.
Simone

**Comment by MaestSi** [comment] 2020-06-01 14:35
Uh, I spotted it! The issue was due to the fact that in the same folder I also had reference.fasta.fai index file. After removing it, it worked smoothly. Could you please confirm that it fails also for you if you generate that file with `samtools faidx reference.fasta`?
Thanks,
Simone

**Comment by mwykes** [comment] 2020-06-01 15:12
When I run `samtools faidx reference.fasta` to create the faidx it also works. Is it possible the reference.fasta index was created on a different fasta file?

**Comment by cjw85** [comment] 2020-06-01 15:20
@MaestSi 

This issue was marked as Enhancement rather than Bug as it was believed to be known what the issue was: not a Bug in medaka itself but rather an input error with the resolution that more informative user feedback should be given than relying on the default error message.

We have an internal issue to make the error more explicit and useful to the user. As your error results from a very particular input error that I would not expect ordinarily to occur for most users, and given Medaka's status as a Research Release, I will now close this issue.

**Closed by cjw85** 2020-06-01 15:20 UTC
Labels: enhancement

**Comment by MaestSi** [comment] 2020-06-01 15:32
Hi @cjw85 , thank you for the explanation.
Dear @mwykes , when rebuilding the index everything went smoothly also for me. You were right, I think I created the fai file on a copy of the file with a different chromosome name, my fault.
Thanks,
Simone
