### ISSUE TITLE
Fail to call methylation

### ISSUE THREAD

**Issue by yyoshiaki** [nanoporetech/medaka#177] opened 2020-06-17 13:17 UTC
Hi,

I'm trying to methylation calling using Medaka (v1.0.1) and NA12878 chr20 data downloaded from [the Nanopolish document](https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html). With commands below, Guppy and Medaka methylation guppy2sam ran successfully with a valid bam file, but medaka methylation call stops without any error. `meth.tsv` was created but empty. 

Commands

```
wget http://s3.climb.ac.uk/nanopolish_tutorial/methylation_example.tar.gz
tar -xvf methylation_example.tar.gz
cd methylation_example

guppy_basecaller -c dna_r9.4.1_450bps_hac.cfg --fast5_out  --compress_fastq -i fast5_files/ -s basecalled/ --device "cuda:0 cuda:1 "

FAST5PATH=./basecalled
REFERENCE=./reference.fasta
OUTBAM=meth.bam
medaka methylation guppy2sam ${FAST5PATH} \
--reference ${REFERENCE} \
--recursive \
| samtools sort -@ 8 | samtools view -b -@ 8 > ${OUTBAM}
samtools index ${OUTBAM}

BAM=meth.bam
OUTPUT=meth.tsv
REGION=chr20:500000-1000000
medaka methylation call --meth cpg ${BAM} ${REFERENCE} ${REGION} ${OUTPUT}
```

The output of medaka methylation call

```
[12:42:16 - Mextract] Processing meth.bam.    
[12:42:16 - Mextract] Calling methylation at cpg sites.    
[12:42:16 - Mextract] Searching for motif 'CG'.  
[12:42:16 - Mextract] Processed 5000000 ref positions (7%) 
[12:42:17 - Mextract] Processed 6000000 ref positions (9%)   
[12:42:19 - Mextract] Processed 8000000 ref positions (12%)    
[12:42:20 - Mextract] Processed 9000000 ref positions (13%)               
[12:42:21 - Mextract] Processed 10000000 ref positions (15%)
```

**Environments**

I tried the commands above in two machines but both are in the same results.

 - Installation method :conda
 - OS: Ubuntu 18.04 and Centos7.6
 - GPU model 2080 and tesla v100
 - Driver Version: 430.50 and 418.39  CUDA Version: 10.1 Cudnn 7

Best,
Yoshiaki

**Comment by cjw85** [comment] 2020-06-17 13:19
Hi,

We are aware of an issue where regions of zero coverage cause the code to fail to process correctly all subsequent positions. This is being fixed as we speak!

**Comment by yyoshiaki** [comment] 2020-06-17 13:28
Thank you for your quick response.
It worked!

**Comment by yyoshiaki** [comment] 2020-06-17 13:31
Sorry, one more question, 
When we want to call methylation for the whole genome region, how should we specify the region option? need to repeat for all the chromosomes and concatenate them all?

**Comment by cjw85** [comment] 2020-06-17 14:22
The region should be specified as e.g. `chr1:10000-20000` or simply `chr1`. Unfortunately yes to process a bam with multiple sequences you will have to run the program multiple times with each reference name in turn.

**Comment by yyoshiaki** [comment] 2020-06-17 14:30
Thank you, I'll try it!

**Comment by snajder-r** [comment] 2020-06-19 09:41
Hi! Sorry for re-opening this issue again. I couldn't find the fix. Has it not been merged into the master branch yet? Or is this a duplicate of another issue that's still open?

**Comment by yyoshiaki** [comment] 2020-06-19 09:48
In my case, I changed `REGION=chr20:500000-1000000` to `REGION=chr20:3633618-64105308` because the test fastq didn't contain reads from chr20:500000-1000000. When I feed the appropriate region, it worked.

**Comment by cjw85** [comment] 2020-06-19 09:55
We have not yet released the fix for this. I will see if we can push it through testing today (though naturally we are a little busy with London Calling).

**Comment by snajder-r** [comment] 2020-06-19 10:40
Hi! Thanks for your reply. I understand - was just confused by the issue being closed, which lead me to believe there was a fix out.

**Comment by cjw85** [comment] 2020-08-05 15:38
I have just create a standalone software for this functionality in medaka which has some bug fixes. The functionality will be removed from medaka in a future release.

https://github.com/nanoporetech/fast5mod

**Closed by cjw85** 2020-08-05 15:38 UTC
Labels: bug
