### ISSUE TITLE
Issue with medaka_consensus and tensorflow

### ISSUE THREAD

**Issue by seanaller** [nanoporetech/medaka#118] opened 2019-12-18 12:10 UTC
Hi there,

I am trying to run medaka_consensus but I am running into the following error:
`AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'`

I installed medaka from conda using the suggested installation approach (a new environment for medaka). I'm running this on a server with CentOS 7.

Full error log:
`[12:06:51 - Predict] Setting tensorflow threads to 16.
Traceback (most recent call last):
  File "/homedirs8/bunit/NGS/Sean/.conda/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/homedirs8/bunit/NGS/Sean/.conda/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 525, in main
    args.func(args)
  File "/homedirs8/bunit/NGS/Sean/.conda/envs/medaka/lib/python3.6/site-packages/medaka/prediction.py", line 107, in predict
    K.set_session(tf.Session(
AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'set_session'
Failed to run medaka consensus.`

**Comment by cjw85** [comment] 2019-12-18 13:49
Hi @seanaller,

Do you have a log from when you created your conda environment? My guess is that conda has installed an incorrect version of tensorflow, despite the fact that the medaka package requires a specific version. You can check the version by running:

    python -c "import tensorflow; print(tensorflow.__version__)"

from within your conda environment.

**Comment by seanaller** [comment] 2019-12-18 13:59
Hi @cjw85,

I've added the output from conda when creating the medaka environment (specifically the package declarations). 
I've managed to get medaka installed and working correctly, although to do this I used the pip install method rather than using conda. 

I've checked the tensorflow version from within the conda installation, which is tensorflow 1.14.0.

```
The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-main
  _tflow_select      pkgs/main/linux-64::_tflow_select-2.3.0-mkl
  absl-py            conda-forge/linux-64::absl-py-0.8.1-py36_0
  astor              conda-forge/noarch::astor-0.7.1-py_0
  bcftools           bioconda/linux-64::bcftools-1.9-h68d8f2e_9
  biopython          conda-forge/linux-64::biopython-1.74-py36h516909a_0
  blas               conda-forge/linux-64::blas-2.14-openblas
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  c-ares             conda-forge/linux-64::c-ares-1.15.0-h516909a_1001
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py36_0
  cffi               conda-forge/linux-64::cffi-1.13.2-py36h8022711_0
  curl               conda-forge/linux-64::curl-7.65.3-hf8cf82a_0
  decorator          conda-forge/noarch::decorator-4.4.1-py_0
  gast               conda-forge/noarch::gast-0.3.2-py_0
  google-pasta       conda-forge/noarch::google-pasta-0.1.8-py_0
  grpcio             conda-forge/linux-64::grpcio-1.23.0-py36he9ae1f9_0
  gsl                conda-forge/linux-64::gsl-2.5-h294904e_1
  h5py               conda-forge/linux-64::h5py-2.7.1-py36_2
  hdf5               conda-forge/linux-64::hdf5-1.10.1-2
  htslib             bioconda/linux-64::htslib-1.9-h244ad75_9
  intervaltree       conda-forge/noarch::intervaltree-3.0.2-py_0
  keras-applications conda-forge/noarch::keras-applications-1.0.8-py_1
  keras-preprocessi~ conda-forge/noarch::keras-preprocessing-1.1.0-py_0
  krb5               conda-forge/linux-64::krb5-1.16.4-h2fd8d38_0
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libcurl            conda-forge/linux-64::libcurl-7.65.3-hda55be3_0
  libdeflate         conda-forge/linux-64::libdeflate-1.3-h516909a_0
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-hdf63c60_0
  libgfortran        conda-forge/linux-64::libgfortran-3.0.0-1
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.3.0-hdf63c60_2
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  liblapacke         conda-forge/linux-64::liblapacke-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_5
  libprotobuf        conda-forge/linux-64::libprotobuf-3.11.2-h8b12597_0
  libssh2            conda-forge/linux-64::libssh2-1.8.2-h22169c7_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_0
  mappy              bioconda/linux-64::mappy-2.17-py36h84994c4_0
  markdown           conda-forge/noarch::markdown-3.1.1-py_0
  medaka             bioconda/linux-64::medaka-0.11.1-py36hbcae180_0
  minimap2           bioconda/linux-64::minimap2-2.17-h8b12597_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  networkx           conda-forge/noarch::networkx-2.4-py_0
  numpy              pkgs/main/linux-64::numpy-1.16.1-py36h99e49ec_1
  numpy-base         pkgs/main/linux-64::numpy-base-1.16.1-py36h2f8d375_1
  ont-fast5-api      bioconda/noarch::ont-fast5-api-2.0.1-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1d-h516909a_0
  parasail-python    bioconda/linux-64::parasail-python-1.1.19-py36h8b12597_0
  perl               conda-forge/linux-64::perl-5.26.2-h516909a_1006
  pip                conda-forge/linux-64::pip-19.3.1-py36_0
  progressbar33      conda-forge/noarch::progressbar33-2.4-py_0
  protobuf           conda-forge/linux-64::protobuf-3.11.2-py36he1b5a44_0
  pycparser          conda-forge/linux-64::pycparser-2.19-py36_1
  pyfaidx            bioconda/noarch::pyfaidx-0.5.7-py_0
  pysam              bioconda/linux-64::pysam-0.15.3-py36hbcae180_3
  python             conda-forge/linux-64::python-3.6.7-h357f687_1006
  pyvcf              conda-forge/linux-64::pyvcf-0.6.8-py36_1000
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  samtools           bioconda/linux-64::samtools-1.9-h10a08f8_12
  scipy              conda-forge/linux-64::scipy-1.3.3-py36h921218d_0
  setuptools         conda-forge/linux-64::setuptools-42.0.2-py36_0
  six                conda-forge/linux-64::six-1.13.0-py36_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.1.0-py_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tensorboard        conda-forge/linux-64::tensorboard-1.14.0-py36_0
  tensorflow         pkgs/main/linux-64::tensorflow-1.14.0-mkl_py36h2526735_0
  tensorflow-base    pkgs/main/linux-64::tensorflow-base-1.14.0-mkl_py36h7ce6ba3_0
  tensorflow-estima~ conda-forge/linux-64::tensorflow-estimator-1.14.0-py36h5ca1d4c_0
  termcolor          conda-forge/noarch::termcolor-1.1.0-py_2
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  werkzeug           conda-forge/noarch::werkzeug-0.16.0-py_0
  whatshap           bioconda/linux-64::whatshap-0.18-py36h6bb024c_0
  wheel              conda-forge/linux-64::wheel-0.33.6-py36_0
  wrapt              conda-forge/linux-64::wrapt-1.11.2-py36h516909a_0
  xopen              conda-forge/linux-64::xopen-0.8.4-py36_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
```

**Comment by cjw85** [comment] 2019-12-18 14:13
Thanks for reporting back,

I just created a new conda environment and have an identical package specification to yours, but cannot reproduce the error. If you are happy with your pip-based installation, may I close this issue?

**Comment by seanaller** [comment] 2019-12-18 16:00
No worries. And how weird, I'm assuming it's probably something with the conda installation on my end. But yes, happy for you to close it as it's working fine with pip now.

Thanks.

**Closed** 2019-12-18 16:07 UTC
Labels: conda
